### ISSUE TITLE
Unable to successfully login (invalid authentication)

### ISSUE THREAD

**Issue by eosho** [tronikos/opower-hacs#9]
I am a Pepco user in Maryland. Tried logging into my account with my username and passed (used to login to the Pepco website) & get invalid authentication error. Is there something I am missing?

**Comment by tronikos** [comment]
Pepco is untested. Somebody shared their username/password with me and I was able to add support for BGE and then for all other Exelon subsidiaries since they share similar login but they are untested. If you want to share your username/temp password with me you can reach out to https://community.home-assistant.io/u/tronikos or find tronikos in the Home Assistant discord channel. First, make sure you don't have two-factor authentication enabled since that is not supported.

**Comment by eosho** [comment]
Looks to be working now. Although, cost data is not showing. 
![Screenshot_20230713-164757~2](https://github.com/tronikos/opower-hacs/assets/10321481/233bc592-494e-4e88-8c22-0090b39ce1d1)
